### ISSUE TITLE
关于clip4cmr

### ISSUE THREAD

**Issue by AwakerLee** [TwT520Ly/PyTorch-Geometric-Study#2]

**Comment by AwakerLee** [comment]
联系方式qq:1339228215

**Comment by FutureTwT** [comment]
您好，首先CLIP4CMR可以跑通，其次建议您在适当的位置提出issue，比如将运行错误整理后提交到CLIP4CMR的issue中

**Comment by AwakerLee** [comment]
不好意思,原github上的代码好像不全





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FutureTwT/PyTorch-Geometric-Study] ,clip4cmr (Issue #2)





 
您好，首先CLIP4CMR可以跑通，其次建议您在适当的位置提出issue，比如将运行错误整理后提交到CLIP4CMR的issue中

**Comment by AwakerLee** [comment]
您跑通过代码码






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FutureTwT/PyTorch-Geometric-Study"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FutureTwT/PyTorch-Geometric-Study] ,clip4cmr (Issue #2)





 
您好，首先CLIP4CMR可以跑通，其次建议您在适当的位置提出issue，比如将运行错误整理后提交到CLIP4CMR的issue中

**Comment by FutureTwT** [comment]
建议您在适当的位置提出issue，比如将运行错误整理后提交到CLIP4CMR的issue中
